### PR TITLE
Application module fix

### PR DESCRIPTION
**Pull request by lnknguyen**
Contents:
- Fix calculation of application usage duration
- Update sample data for AWARE application module
- Update test for application module
- Some small linting

### CODE REVIEW

**Comment by rantahar** [comment]
Thanks, I will take a look and fix the tests.

**Comment by rantahar** [comment]
Hmm... Did linting cause the test to fail? In multiple places, but not in the app tests? This is interesting :thinking:

**Comment by lnknguyen** [comment]
oh, I think the tests failed because I modified the sample data to test some edge cases. maybe it is better if I revert the sample data to its original states and append the edge cases (instead of replacing the whole file).

**Comment by rantahar** [comment]
Thanks!

**Pull request merged**
